[package]
name = "aemacs-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "aemacs_core"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
ropey = { workspace = true }
log = { workspace = true }
gpui = { workspace = true }
async-channel = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tree-sitter = { workspace = true }
tree-sitter-rust = { workspace = true }
