[package]
name = "aemacs-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "aemacs_core"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
ropey = { workspace = true }
log = { workspace = true }
gpui = { workspace = true }
async-channel = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-rust = { workspace = true }
tree-sitter-python = { workspace = true }
tree-sitter-go = { workspace = true }
tree-sitter-haskell = { workspace = true }
tree-sitter-c = { workspace = true }
tree-sitter-cpp = { workspace = true }
tree-sitter-javascript = { workspace = true }
notify = { workspace = true }
ron = { workspace = true }
dirs = { workspace = true }
imap = "3.0.0-alpha.12"
native-tls = "0.2"
matrix-sdk = { version = "0.7.1", features = ["native-tls"] }

[dev-dependencies]
tempfile = { workspace = true }
