[package]
name = "aemacs-bridge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "aemacs_bridge"
path = "src/lib.rs"

[dependencies]
pyo3 = { workspace = true }
tree-sitter = { workspace = true }
anyhow = { workspace = true }
aemacs-core = { workspace = true }
log = { workspace = true }
