use serde::{Deserialize, Serialize};

/// Represents a standard diagnostic signal, typically generated by an LSP or linter.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagnosticSignal {
    /// The physical path to the file containing the diagnostic.
    pub file_path: String,
    /// The 1-based line number where the issue was detected.
    pub line_number: usize,
    /// The human-readable diagnostic message.
    pub message: String,
    /// The severity level (e.g., Error, Warning, Info).
    pub severity: String,
}

/// Represents a signal indicating that a text buffer has been physically modified.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BufferModifiedSignal {
    /// The physical path to the modified file.
    pub file_path: String,
    /// A short string describing the nature of the change.
    pub diff_chunk: String,
}

/// A generic signal payload for custom events not covered by specialized types.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenericSignal {
    /// Detailed description of the custom signal.
    pub details: String,
}

/// Represents a progress update from an executing tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolProgressSignal {
    /// The unique name of the tool.
    pub tool_name: String,
    /// Whether the tool is currently running or has finished.
    pub is_running: bool,
}

/// Represents a periodic heartbeat signal used to trigger routine autonomous tasks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimePulseSignal {
    /// The absolute number of ticks since the system started.
    pub tick_count: u64,
    /// The frequency of the heartbeat in seconds.
    pub interval_seconds: u64,
}

// --- ACO-029: The Schema of Meaning ---

/// Defines the primary high-level goals or intents interpreted from system signals.
/// These guide the autonomous agents in deciding their next course of action.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum AutonomousIntent {
    /// Instructs the agent to perform a technical review of a recent change.
    ReviewChange,
    /// Instructs the agent to investigate and fix a detected build or runtime error.
    FixBuildError,
    /// Instructs the agent to process and summarize a large block of external information.
    SummarizeExternalData,
    /// Instructs the agent to perform a routine status check or mental inventory.
    RoutineCheck,
    /// Instructs the agent to handle a significant burst of simultaneous events.
    BulkUpdate,
}

/// Encapsulates the full context of an autonomous trigger, including intent, location, and metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalContext {
    /// The high-level intent derived from the signal.
    pub intent: AutonomousIntent,
    /// The physical file path most relevant to the signal, if any.
    pub file_path: Option<String>,
    /// A relevant snippet of text (e.g., a build error or a code diff).
    pub snippet: Option<String>,
    /// Key-value pairs providing additional technical context.
    pub metadata: std::collections::HashMap<String, String>,
}
