[package]
name = "aemacs-lsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tower-lsp = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
aemacs-core = { workspace = true }
log = { workspace = true }

[lints]
workspace = true