use std::fmt;

use serde::{Deserialize, Serialize};

/// Represents the role of a participant in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum Role {
    /// The system prompt that sets the behavior and constraints of the model.
    #[serde(rename = "system")]
    System,
    /// The human user interacting with the model.
    #[serde(rename = "user")]
    User,
    /// The AI assistant generating responses.
    #[serde(rename = "assistant")]
    Assistant,
    /// A role representing the output of a tool execution.
    #[serde(rename = "tool")] // New Role for Tool Outputs
    Tool,
}

/// Represents the content of a message, which can be either a simple string
/// or a complex collection of content parts (e.g., text and images).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Content {
    /// Simple text content.
    Text(String),
    /// A sequence of distinct content parts.
    Parts(Vec<ContentPart>),
}

impl From<String> for Content {
    fn from(s: String) -> Self {
        Self::Text(s)
    }
}

impl From<&str> for Content {
    fn from(s: &str) -> Self {
        Self::Text(s.to_string())
    }
}

impl fmt::Display for Content {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Text(s) => write!(f, "{s}"),
            Self::Parts(parts) => {
                for part in parts {
                    match part {
                        ContentPart::Text { text } => write!(f, "{text}")?,
                        ContentPart::ImageUrl { .. } => {},
                    }
                }
                Ok(())
            },
        }
    }
}

/// Represents a single part of a message's content.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentPart {
    /// A text segment.
    Text { text: String },
    /// An image reference.
    ImageUrl { image_url: ImageUrl },
}

/// Represents a URL for an image.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageUrl {
    /// The raw URL or data-URI of the image.
    pub url: String,
}

// --- Tooling ---

/// Represents a call to an external tool initiated by the AI model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// A unique identifier for this specific tool call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of call (usually "function").
    #[serde(rename = "type")]
    pub call_type: String, // Usually "function"
    /// The specific function being invoked and its arguments.
    pub function: ToolCallFunction,
}

/// Represents the specific function details within a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallFunction {
    /// The name of the function to execute.
    pub name: String,
    /// The arguments for the function, provided as a JSON string.
    pub arguments: String, // JSON string
}

/// Represents a single message within a conversational exchange.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// The role of the message sender.
    pub role: Role,
    /// The primary content of the message.
    pub content: Content,
    /// Optional tool calls generated by the model during this message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,

    /// For Tool Outputs: The ID of the tool call this message is responding to.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,

    /// The timestamp when the message was created.
    #[serde(default = "chrono::Utc::now")]
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

impl Message {
    /// Creates a new message with the given role and content.
    pub fn new(role: Role, content: impl Into<Content>) -> Self {
        Self {
            role,
            content: content.into(),
            tool_calls: None,
            tool_call_id: None,
            timestamp: chrono::Utc::now(),
        }
    }

    /// Creates a new system message.
    pub fn system(content: impl Into<Content>) -> Self {
        Self::new(Role::System, content)
    }

    /// Creates a new user message.
    pub fn user(content: impl Into<Content>) -> Self {
        Self::new(Role::User, content)
    }

    /// Creates a new assistant message.
    pub fn assistant(content: impl Into<Content>) -> Self {
        Self::new(Role::Assistant, content)
    }

    /// Creates a new user message containing both text and an image.
    pub fn user_with_image(text: impl Into<String>, image_url: impl Into<String>) -> Self {
        let parts = vec![
            ContentPart::Text { text: text.into() },
            ContentPart::ImageUrl { image_url: ImageUrl { url: image_url.into() } },
        ];
        Self {
            role: Role::User,
            content: Content::Parts(parts),
            tool_calls: None,
            tool_call_id: None,
            timestamp: chrono::Utc::now(),
        }
    }
}

/// Specific configuration options for the Ollama inference engine.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct OllamaOptions {
    /// The size of the context window in tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_ctx: Option<u32>,
    /// How long the model should remain in VRAM after the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub keep_alive: Option<String>,
}

/// Represents a request sent to an AI backend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AIRequest {
    /// The name of the model to use.
    pub model: String,
    /// The conversation history leading up to this request.
    pub messages: Vec<Message>,
    /// The sampling temperature (creativity control).
    pub temperature: f32,
    /// Whether to stream the response as it is generated.
    pub stream: bool,
    /// Backend-specific options.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<OllamaOptions>,
    /// Definitions of tools available for the model to call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<serde_json::Value>>, // Tool Definitions
}

impl Default for AIRequest {
    fn default() -> Self {
        Self {
            model: "default".to_string(),
            messages: Vec::new(),
            temperature: 0.7,
            stream: true,
            options: None,
            tools: None,
        }
    }
}

// --- Model Registry (ACO-035) ---

/// Defines the available hardware tiers for model selection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModelTier {
    /// Optimized for laptops and low VRAM devices.
    Low,
    /// Optimized for high-end workstations.
    Medium,
    /// Optimized for server-grade multi-GPU systems.
    High,
}

/// Defines the specialized role of a model within the Bicameral pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModelRole {
    /// The executive hemisphere focused on technical analysis and tool use.
    Logic,
    /// A general-purpose creative model.
    Creative,
    /// The voice hemisphere focused on persona fidelity and prose synthesis.
    Roleplay,
}

/// Static definition of an AI model available in the registry.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ModelDefinition {
    /// The physical name of the model (for backend calls).
    pub name: &'static str,
    /// A human-readable label for the UI.
    pub label: &'static str,
    /// The hardware tier this model targets.
    pub tier: ModelTier,
    /// The specialized role of this model.
    pub role: ModelRole,
    /// Minimum VRAM required to load the weights.
    pub base_vram_gb: f32,
    /// Rate of VRAM consumption for the KV cache per 1000 tokens.
    pub kv_rate_gb_per_1k: f32,
    /// Absolute maximum context window supported by the model.
    pub max_context: u32,
    /// Plaintext description of license terms.
    pub license_constraints: &'static str,
    /// Detailed summary of the model's capabilities and training.
    pub model_description: &'static str,
    /// Whether this model supports function calling/tool use.
    pub supports_tools: bool,
}

/// The global registry of validated models for local inference.
pub const MODELS: &[ModelDefinition] = &[
    // ... rest of file (kept constant for this edit)
    // TIER: LOW (Laptops, < 8GB VRAM)
    // ==========================================
    ModelDefinition {
        name: "dolphin3:8b",
        label: "Dolphin 3.0 8B",
        tier: ModelTier::Low,
        role: ModelRole::Creative,
        base_vram_gb: 5.0,
        kv_rate_gb_per_1k: 0.015,
        max_context: 131_072,
        license_constraints: "Llama 3.1 Community License. Free for commercial and freelance use. Restriction only applies if your product exceeds 700 million monthly active users.",
        model_description: "The Unrestricted Sparring Partner. Built on Llama 3.1 but explicitly fine-tuned for high emotional intelligence, creative lateral thinking, and zero refusals. The perfect lightweight choice for local, highly conversational Pair-Programming and deep architectural brainstorming without moralizing guardrails.",
        supports_tools: true,
    },
    ModelDefinition {
        name: "llama-3.1-8b-stheno-v3.4-q4_K_M",
        label: "Stheno v3.4 8B",
        tier: ModelTier::Low,
        role: ModelRole::Roleplay,
        base_vram_gb: 4.9,
        kv_rate_gb_per_1k: 0.015,
        max_context: 131_072,
        license_constraints: "Llama 3.1 Community License. Free for commercial and freelance use. Restriction only applies if your product exceeds 700 million monthly active users.",
        model_description: "The Modernized Method Actor. Rebuilt entirely on the Llama 3.1 architecture, natively unlocking the massive 128k context window via optimized RoPE scaling. Exceptional at maintaining deep, persistent narrative states and complex persona heuristics without context collapse over prolonged sessions.",
        supports_tools: false,
    },
    // ==========================================
    // TIER: MEDIUM (Workstations, ~12-26GB VRAM)
    // ==========================================
    ModelDefinition {
        name: "dolphin-3.0-mistral-24b-q4_K_M",
        label: "Dolphin 3.0 24B",
        tier: ModelTier::Medium,
        role: ModelRole::Creative,
        base_vram_gb: 14.3,
        kv_rate_gb_per_1k: 0.022,
        max_context: 32768,
        license_constraints: "Apache 2.0 License. 100% free for unrestricted commercial and enterprise use.",
        model_description: "The Unrestricted Polymath Core. Built on Mistral's dense 24B parameter network, completely replacing legacy MoE routing. Highly intelligent, fully uncensored, and explicitly fine-tuned by Cognitive Computations for deterministic tool execution, complex mathematics, and agentic workflows.",
        supports_tools: true,
    },
    ModelDefinition {
        name: "magnum:12b",
        label: "Magnum v2 12B",
        tier: ModelTier::Medium,
        role: ModelRole::Roleplay,
        base_vram_gb: 7.5,
        kv_rate_gb_per_1k: 0.025,
        max_context: 128_000,
        license_constraints: "Apache 2.0 License. 100% free for unrestricted commercial and enterprise use.",
        model_description: "The Contextual Method Actor. Built on Mistral Nemo, offering a massive 128k context window crucial for maintaining long-running personas and deep narrative states without forgetting details. Renowned for generating vivid text and staying flawlessly in character across massive sessions.",
        supports_tools: false,
    },
    // ==========================================
    // TIER: HIGH (Heavy Compute, 40GB+ VRAM)
    // ==========================================
    ModelDefinition {
        name: "llama3.3:70b",
        label: "Llama 3.3 70B",
        tier: ModelTier::High,
        role: ModelRole::Creative,
        base_vram_gb: 40.0,
        kv_rate_gb_per_1k: 0.050,
        max_context: 131_072,
        license_constraints: "Llama 3.3 Community License. Free for commercial and enterprise use.",
        model_description: "The SOTA Powerhouse. Distills the reasoning capabilities of Meta's massive 405B model into a highly efficient 70B footprint. While fully aligned, its sheer intelligence makes it the ultimate conversational sparring partner for complex code refactoring, deep architectural planning, and lateral problem-solving.",
        supports_tools: true,
    },
    ModelDefinition {
        name: "euryale:70b",
        label: "Euryale v2.2 70B",
        tier: ModelTier::High,
        role: ModelRole::Roleplay,
        base_vram_gb: 40.0,
        kv_rate_gb_per_1k: 0.050,
        max_context: 131_072,
        license_constraints: "Llama 3.1 Community License. Free for commercial and enterprise use.",
        model_description: "The Enterprise Persona. The absolute pinnacle of open-weights roleplay. It provides the deep, lateral thinking and conversational nuance of legacy models like Miqu, but is built on a clean Llama 3.1 foundation, making it fully compliant and safe for corporate environments.",
        supports_tools: false,
    },
];

pub const CONTEXT_OPTIONS: &[u32] = &[4096, 8192, 16384, 32768, 65536, 131_072];

pub fn get_models_for_tier(tier_str: &str) -> Vec<&'static ModelDefinition> {
    let target_tier = match tier_str.to_uppercase().as_str() {
        "LOW" => ModelTier::Low,
        "MEDIUM" => ModelTier::Medium,
        "HIGH" => ModelTier::High,
        _ => {
            tracing::warn!("Unknown hardware tier '{}', defaulting to LOW", tier_str);
            ModelTier::Low
        },
    };

    MODELS.iter().filter(|m| m.tier == target_tier).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_get_models_for_tier_high() {
        let models = get_models_for_tier("HIGH");
        assert!(!models.is_empty(), "Should return high-tier models.");
        for model in models {
            assert_eq!(model.tier, ModelTier::High);
        }
    }

    #[test]
    fn test_get_models_for_tier_case_insensitive() {
        let models = get_models_for_tier("medium");
        assert!(!models.is_empty());
        for model in models {
            assert_eq!(model.tier, ModelTier::Medium);
        }
    }

    #[test]
    fn test_get_models_for_tier_invalid_fallback() {
        // Fallback to LOW
        let models = get_models_for_tier("TOASTER");
        assert!(!models.is_empty());
        for model in models {
            assert_eq!(model.tier, ModelTier::Low);
        }
    }
}
