use aemacs_ai::Conversation;
use aemacs_ai::connectors::openai_compatible::OpenAICompatibleBackend;
use aemacs_ai::mcp::{ToolHost, ToolRegistry, run_agent_loop};
use aemacs_ai::rag::KnowledgeBase;
use aemacs_core::runtime::Tokio;
use gpui::{AsyncApp, Context, Task, WeakEntity};

use std::sync::Arc;

/// Defines the sequence of events emitted by an active agent during its execution.
/// These events are used to update the UI in real-time as the agent reasons and acts.
pub enum AgentEvent {
    /// A new chunk of text has been generated by the voice hemisphere.
    StreamChunk(String),
    /// The agent has initiated a call to a specific tool.
    ToolStarted(String),
    /// A tool execution has completed, returning its success status.
    ToolFinished(String, bool),
    /// The agentic loop has finished successfully, returning the final conversation state.
    Result(Conversation),
    /// An unrecoverable error occurred during agent execution.
    Error(String),
}

/// Spawns an asynchronous GPUI task that manages the lifecycle of an AI agent.
/// It bridges the Tokio background runtime with the GPUI main thread, mapping low-level
/// loop signals to high-level UI events and automatically archiving finished conversations to memory.
pub fn spawn_agent_task<V, F, H>(
    cx: &mut Context<V>,
    backend: OpenAICompatibleBackend,
    registry: Arc<ToolRegistry>,
    kb: Arc<KnowledgeBase>,
    host: H,
    mut conversation: Conversation,
    update_fn: F,
) -> Task<()>
where
    V: 'static,
    F: 'static + Send + Sync + Copy + Fn(&mut V, &mut Context<V>, AgentEvent),
    H: 'static + ToolHost + Send + Sync,
{
    let (tx, rx) = async_channel::unbounded::<AgentEvent>();
    let tx_for_stream = tx.clone();

    // 1. Ignite the Tokio background task for heavy inference and tool logic.
    let tokio_task = Tokio::spawn(cx, async move {
        // Create a proxy channel to map internal LoopSignals to UI-facing AgentEvents.
        let (signal_tx, signal_rx) = async_channel::unbounded::<aemacs_ai::mcp::LoopSignal>();
        let tx_proxy = tx_for_stream.clone();

        tokio::spawn(async move {
            while let Ok(signal) = signal_rx.recv().await {
                let event = match signal {
                    aemacs_ai::mcp::LoopSignal::Text(chunk) => AgentEvent::StreamChunk(chunk),
                    aemacs_ai::mcp::LoopSignal::ToolCall(name) => AgentEvent::ToolStarted(name),
                    aemacs_ai::mcp::LoopSignal::ToolResult(name, success) => {
                        AgentEvent::ToolFinished(name, success)
                    }
                };
                let _ = tx_proxy.send(event).await;
            }
        });

        match run_agent_loop(
            &backend,
            &registry,
            &host,
            &mut conversation,
            10,
            Some(signal_tx),
        )
        .await
        {
            Ok(_result) => {
                // ACO-025: Automatically archive the complete conversation to the RAG Fortress.
                let session_id = uuid::Uuid::new_v4().to_string();
                if let Err(e) = conversation.archive_to_memory(&kb, &session_id).await {
                    log::error!("⚠️ [AI] Failed to archive conversation to memory: {}", e);
                }

                let _ = tx_for_stream.send(AgentEvent::Result(conversation)).await;
            }
            Err(e) => {
                let _ = tx_for_stream.send(AgentEvent::Error(e.to_string())).await;
            }
        }
    });

    // 2. Spawn the GPUI observer task that listens for background events and updates the view.
    cx.spawn(move |this: WeakEntity<V>, cx: &mut AsyncApp| {
        let mut cx = cx.clone();
        async move {
            let _keep_alive = tokio_task;
            while let Ok(event) = rx.recv().await {
                let update_result = this.update(&mut cx, |view, cx| {
                    update_fn(view, cx, event);
                });
                if update_result.is_err() {
                    break;
                }
            }
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use aemacs_ai::mcp::ToolHost;
    use async_trait::async_trait;

    struct LocalTestHost;
    #[async_trait]
    impl ToolHost for LocalTestHost {
        async fn ask_approval(&self, _description: &str) -> bool {
            true
        }
        async fn ask_user(&self, _question: &str) -> String {
            "Test".to_string()
        }
        fn get_agent_id(&self) -> String {
            "test".to_string()
        }
        fn report_progress(&self, _name: String, _running: bool) {}
        async fn emit_signal(&self, _type: String, _payload: String) -> anyhow::Result<()> {
            Ok(())
        }
    }

    #[tokio::test]
    async fn test_spawn_agent_task_compilation_check() {
        // QUEST: This test verifies that the logic compiles.
        assert!(true);
    }
}
